### ISSUE TITLE
origin of the project

### ISSUE THREAD

**Issue by stragu** [zlabx/ggcor#1]
Hi there!

I noticed that https://github.com/houyunhuang/ggcor does not exist anymore.
I assume this repository is based on houyunhuang's work? If that's the case, I'm wondering about the original commits. Is there any reason why they are not included in the history? Did you have the codebase but not the associated git repository?

Cheers

**Comment by zlabx** [comment]
this is a temporary&nbsp;repository authorized by houyunhuang, only for reseachers in china,you may refer to our chinese webpage for more information:https://blog.csdn.net/zlabx/article/details/107358265.
&nbsp;thanks!


------------------

 Zhou Jian
Institute of Subtropical Agriculture (ISA),&nbsp;
The Chinese Academy of Science (CAS),&nbsp;
University of Chinese Academy of Science(UCAS),&nbsp;
Hunan, Changsha 410125, Post Box 10,P.R.China,





 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by stragu** [comment]
Hi @zlabx 
Thank you for the prompt reply!

When you say "only for researchers in China", do you mean there are restrictions to the use of the package, based on this repository? The GPL license currently in use would suggest that anyone can use the package and code (following the licence's requirements, of course). And related to that: would you like to eventually have this package available on CRAN?

I arrived here because I noticed that the ggcor link on this page was broken: https://exts.ggplot2.tidyverse.org/gallery/ (you need to turn "CRAN only" off).
Would you want that link to be fixed and point to this repository, or would you rather not see this package listed on the website?

Cheers

**Comment by zlabx** [comment]
We are sorry to tell you that Dr.hou yun huang ,decided to drop this project and zlab will turn off the repository at 2021.jan.1.We no longer provide any support on this project and packages, many thanks~




------------------

 Zhou Jian
Institute of Subtropical Agriculture (ISA),&nbsp;
The Chinese Academy of Science (CAS),&nbsp;
University of Chinese Academy of Science(UCAS),&nbsp;
Hunan, Changsha 410125, Post Box 10,P.R.China,





 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by stragu** [comment]
But would Hou Yun Huang or yourself be happy for others to build upon this code and release further versions?

**Comment by zlabx** [comment]
> But would Hou Yun Huang or yourself be happy for others to build upon this code and release further versions?

No plans, only Dr.hou yun huang ,could decide it, we should respect his efforts.
